### ISSUE TITLE
Images not showing properly

### ISSUE THREAD

**Issue by eMUQI** [QhelDIV/Intro2research#1]
**To Reproduce the bug**
1. Go to "http://vcc.tech/courses/i2r/feng/"
2. Scroll down to 'Potential Topics'
3. See error
![image](https://user-images.githubusercontent.com/32332228/56077631-13bb2e80-5e11-11e9-9626-1df91b4bbf09.png)

**Expected behavior**
Picture is displayed

**Comment by eMUQI** [comment]
![image](https://user-images.githubusercontent.com/32332228/56077727-40237a80-5e12-11e9-91fe-75501479e3a1.png)
![image](https://user-images.githubusercontent.com/32332228/56077769-a0b2b780-5e12-11e9-99c2-725dd8880d6c.png)

**Comment by QhelDIV** [comment]
Actually, the text version is converted from ppt and the converter has some bugs. 
The text version is used to provide copyable links for image version, so please read image version instead. :D
